name: nityanandadas
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9d35537a-cba7-4de9-80d6-2f02bf62e53f.jpg
layout_spectrum: 0.886824
typography_spectrum: 1
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.427262
  lightness: 0.717877
  saturation: 0.223321
  rhythmicContrast: 0.519675
purpose: []
title: Nityananda Das
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
