analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.427262
  lightness: 0.717877
  rhythmicContrast: 0.519675
  saturation: 0.223321
cta: {}
layout_spectrum: 0.886824
name: nityanandadas
opengraph: {}
purpose: []
typography_spectrum: 1
